'use client';
import { Context, contextModels, points } from './data';
import { rateFor, ratePoints } from './pricing-data';
import { packages } from './credits';
import Image from 'next/image';
export default function Pricing({ context, getCredits, contact }: { contact: () => void; context: Context; getCredits: (credits: number) => void }) {
  const available = contextModels(context);
  const groups = [{ title: '语音生成', ids: available.filter(m => m.kind === 'TTS').map(m => m.id) }, { title: '语音转写', ids: available.filter(m => m.kind === 'ASR').map(m => m.id) }];
  return <main id="main-content" className="p-main p-pricing"><header className="p-pricing-heading"><div><h1>积分包</h1><p>选择适合的积分包，积分可用于所有 API 调用。</p></div><span>积分自购买日起一年内有效</span></header><section className="p-pricing-packs" aria-label="积分包列表">{packages.map(pack => <article key={pack.credits}>{pack.discount ? <span className="p-pack-corner">{pack.discount}</span> : null}<h2 className="p-pack-credits"><Image src="/platform/point.svg" width={20} height={20} alt="" />{pack.credits} 积分</h2><div className="p-pack-price-box"><div className="p-pack-price-line"><strong>¥ {pack.price}</strong>{pack.list ? <del>¥ {pack.list}</del> : null}</div></div><button className="p-button p-primary p-pack-buy" onClick={() => getCredits(pack.credits)}>购买</button></article>)}</section><section className="p-pricing-business"><div><h3>商务定制</h3><p>针对企业方案定制配额用量、提供专属服务、SLA 与技术支持</p></div><button className="p-text-button" onClick={contact}>联系我们</button></section><section className="p-pricing-rates"><header><h2>模型计费标准</h2><span>{context === 'enterprise' ? '星河科技 · 企业专属计费规则，仅在消耗积分时生效' : '调用统一按积分结算；人民币仅用于购买积分包。'}</span></header>{groups.map(group => <section className="p-rate-group" key={group.title}><header><h3>{group.title}</h3></header><div className="p-table-scroll"><table className={context === 'enterprise' ? 'p-rate-enterprise' : 'p-rate-personal'}><colgroup>{[32, 23, 25, 20].map((width, index) => <col key={index} style={{ width: `${width}%` }} />)}</colgroup><thead><tr><th>模型</th><th>计费方式</th><th className="p-number">计费规则</th><th className="p-number">最低扣费</th></tr></thead><tbody>{available.filter(m => group.ids.includes(m.id)).map(m => { const rate = rateFor(context, m.id); return <tr key={m.id}><td>{m.id}</td><td>{m.kind === 'TTS' ? '按输入字符' : '按输入音视频时长'}</td><td className="p-number">{ratePoints(rate).toFixed(2)} 积分 / {rate.basisLabel}</td><td className="p-number">{points(rate.minimumCents)} 积分 / 次</td></tr>; })}</tbody></table></div></section>)}</section><section className="p-pricing-rules"><h2>购买与结算规则</h2><ul>{context === 'enterprise' ? <li>企业调用按对应模型的企业价格扣除积分。</li> : null}<li>按请求实际用量计算积分，折后消耗低于最低扣费时，按最低积分扣除。</li><li>账单保留调用时的计费标准，后续调整不影响历史记录。</li></ul></section></main>;
}
