"use client";
import { useState } from "react";
import { enterpriseEntitlements, projectName, ApiKeyRecord, canAct, canManageCredentials, initialMembers, Member, notice, ProjectContext, resourceLabels, Role, ResourceAllocation, View, WorkspaceProject } from "./data";
import { DataTable, Icon, Metric, PageHeader, Status, Tabs } from "./ui";
import { KeyLifecycleDialog, QuotaRequestDialog, ResourceDialog } from "./workflows";
import { credentialTabs as tabs } from "./credential-navigation";

// Product rules are maintained in the PRD rather than rendered as explanatory cards:
// 企业统一结算；Member 是登录、资源策略与用量归因主体；API Key 继承 Member 策略。
// 费用中心只提供商务已确认的余额、权益、用量与对账只读查询。
export function Credentials({view,go,openKey,projectContext,setProjectContext,role,member,members=initialMembers,workspaceProjects,apiKeys,selectedKey,selectKey,updateKey,createWorkspaceProject,onQuotaRequest}:{view:View;go:(v:View)=>void;openKey:()=>void;projectContext:ProjectContext;setProjectContext:(project:ProjectContext)=>void;role:Role;member:Member;members?:Member[];workspaceProjects:WorkspaceProject[];apiKeys:ApiKeyRecord[];selectedKey:ApiKeyRecord;selectKey:(key:ApiKeyRecord)=>void;updateKey:(key:ApiKeyRecord,action:"rotate"|"disable")=>void;createWorkspaceProject:(name:string)=>void;onQuotaRequest?:(projectId:string,summary:string)=>void}){
 const [resourceDialog,setResourceDialog]=useState<"project"|null>(null);
 const [selectedProject,setSelectedProject]=useState(workspaceProjects[0]);
 const currentProject=workspaceProjects.find(item=>item.id===projectContext)??selectedProject;
 const canCreateProject=canAct(role,"project.create");
 const manageableProjectIds=workspaceProjects.filter(project=>canManageCredentials(role,project.id,member)).map(project=>project.id);
 const canCreateKey=canAct(role,"key.create")&&manageableProjectIds.some(id=>projectContext==="all"||id===projectContext);
 const actorName=role==="Owner"?"企业 Owner":role==="Admin"?"王开发":"李测试";
 const filteredProjects=projectContext==="all"?workspaceProjects:workspaceProjects.filter(project=>project.id===projectContext);
 const filteredKeys=apiKeys.filter(key=>projectContext==="all"||key.projectId===projectContext);
 if(view==="keyDetail")return <KeyDetailV2 go={go} role={role} member={member} apiKey={selectedKey} updateKey={updateKey}/>;
 if(view==="projectDetail")return <ProjectDetail go={go} project={currentProject} apiKeys={apiKeys} setProjectContext={setProjectContext}/>;
 if(view==="projects")return <><Tabs items={tabs} active={view} go={go}/><PageHeader eyebrow="项目与凭证" title="项目" description="管理企业 Workspace 下的项目，以及项目对应的 API Key、配额、用量与日志归属边界。" action={canCreateProject?<button className="btn primary" type="button" onClick={()=>setResourceDialog("project")}>创建项目</button>:<span className="period-chip">{role} · 仅查看授权项目</span>}/><section className="panel table-panel"><DataTable caption="Workspace 项目列表" heads={["项目","负责人","API Keys","用量","RPM 水位","状态","操作"]} rows={filteredProjects.map(p=>[<span className="cell-stack" key={p.id}><b>{p.name}</b><code>{p.id}</code></span>,p.owner,String(p.keys),p.usage,p.rpm,<Status key="s">{p.status}</Status>,<button className="row-action" type="button" key="a" onClick={()=>{setSelectedProject(p);setProjectContext(p.id);go("projectDetail")}}>查看详情 →</button>])}/></section>{resourceDialog?<ResourceDialog kind={resourceDialog} actorName={actorName} close={()=>setResourceDialog(null)} complete={name=>{createWorkspaceProject(name);setResourceDialog(null);notice(`${name} 已创建到云蝠智能 Workspace，Owner / Admin 均可见（Demo）`)}}/>:null}</>;
 if(view==="keys")return <AccountCredentialsView go={go} openKey={openKey} role={role} member={member} apiKeys={apiKeys} selectKey={selectKey}/>;
 return null;
}

function KeyDetailV2({go,role,member,apiKey,updateKey}:{go:(v:View)=>void;role:Role;member:Member;apiKey:ApiKeyRecord;updateKey:(key:ApiKeyRecord,action:"rotate"|"disable")=>void}){
 const [lifecycle,setLifecycle]=useState<"rotate"|"disable"|null>(null);
 const disabled=apiKey.status==="已停用";
 const canManage=canManageCredentials(role,apiKey.projectId,member);
 const rotate=()=>{const next={...apiKey,status:"轮换中" as const,version:apiKey.version+1,lastRotatedAt:"刚刚",masked:"sk_live_••••YF26"};updateKey(next,"rotate")};
 const disable=()=>{const next={...apiKey,status:"已停用" as const,lastUsedAt:"停用于刚刚"};updateKey(next,"disable")};
 return <><button className="back" type="button" onClick={()=>go("keys")}>← 返回 API 凭证</button><PageHeader eyebrow="MEMBER CREDENTIAL" title={apiKey.name} description={`该 Key 归属 Member“${member.name}”，继承该账号的 Voice、Token、RPM 与并发策略。`} action={canManage?<div className="page-actions"><button className="btn secondary" type="button" disabled={disabled} onClick={()=>setLifecycle("rotate")}>轮换 Key</button><button className="btn danger" type="button" disabled={disabled} onClick={()=>setLifecycle("disable")}>停用 Key</button></div>:<span className="period-chip">{role} · 只读</span>}/><section className="fact-grid panel"><div><span>Key</span><code>{apiKey.masked}</code></div><div><span>归属 Member</span><b>{member.name}</b></div><div><span>状态</span><Status tone={disabled?"bad":apiKey.status==="轮换中"?"warn":"good"}>{apiKey.status}</Status></div><div><span>版本</span><b>v{apiKey.version}</b></div></section><section className="two-col"><article className="panel detail-card"><span className="eyebrow">CREDENTIAL POLICY</span><h2>安全与调用范围</h2><dl><div><dt>Scope</dt><dd><code>{apiKey.scopes.join(", ")}</code></dd></div><div><dt>IP 白名单</dt><dd>{apiKey.ipAllowlist}</dd></div><div><dt>有效期</dt><dd>{apiKey.expiresAt}</dd></div><div><dt>归属策略</dt><dd>Member 资源策略</dd></div></dl></article><article className="panel detail-card"><span className="eyebrow">USAGE & AUDIT</span><h2>用量与生命周期</h2><dl><div><dt>创建人 / 时间</dt><dd>{apiKey.createdBy} · {apiKey.createdAt}</dd></div><div><dt>最近轮换</dt><dd>{apiKey.lastRotatedAt}</dd></div><div><dt>最近调用</dt><dd>{apiKey.lastUsedAt}</dd></div><div><dt>本月用量</dt><dd>{apiKey.usage}</dd></div></dl></article></section><section className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">EXPOSURE EVIDENCE</span><h2>完整值接触记录</h2></div><span>{apiKey.exposureEvents.length} 条记录</span></div><DataTable caption="凭证暴露记录" heads={["成员账号","动作","Key 版本","时间"]} rows={apiKey.exposureEvents.map((event,index)=>[<span className="cell-stack" key={`${event.memberEmail}-${index}`}><b>{event.memberName}</b><code>{event.memberEmail}</code></span>,event.action,`v${event.version}`,event.at])}/></section>{lifecycle?<KeyLifecycleDialog mode={lifecycle} apiKey={apiKey} close={()=>setLifecycle(null)} complete={()=>{const mode=lifecycle;setLifecycle(null);mode==="rotate"?rotate():disable()}}/>:null}</>;
}

function MemberKeysView({go,openKey,role,member,apiKeys,selectKey,setProjectContext}:{go:(v:View)=>void;openKey:()=>void;role:Role;member:Member;apiKeys:ApiKeyRecord[];selectKey:(key:ApiKeyRecord)=>void;setProjectContext:(p:ProjectContext)=>void}){
 const manageable=apiKeys.filter(key=>key.status!=="已停用"||role==="Owner");
 return <><Tabs items={tabs} active="keys" go={go}/><PageHeader title="API Keys" description="API Key 归属于 Member 账号；同一账号下的多个 Key 共享资源策略，Project 不参与凭证归属或配额计算。" action={<button className="btn primary" type="button" onClick={openKey}>创建 API Key</button>}/><section className="panel table-panel"><DataTable caption="Member API Key 列表" heads={["名称 / Key","归属 Member","Scope","有效期","最近调用","本月用量","状态","操作"]} rows={manageable.map(key=>[<span className="cell-stack" key={key.id}><b>{key.name}</b><code>{key.masked}</code></span>,key.createdBy===member.name?member.name:key.createdBy,<code key="scope">{key.scopes.join(", ")}</code>,key.expiresAt,key.lastUsedAt,key.usage,<Status key="state" tone={key.status==="已停用"?"bad":key.status==="轮换中"?"warn":"good"}>{key.status}</Status>,<button key="action" className="row-action" type="button" onClick={()=>{selectKey(key);setProjectContext("all");go("keyDetail")}}>管理 →</button>])}/></section></>;
}

function QuotaView({go,projectContext,workspaceProjects,role,onQuotaRequest}:{go:(view:View)=>void;projectContext:ProjectContext;workspaceProjects:WorkspaceProject[];role:Role;onQuotaRequest?:(projectId:string,summary:string)=>void}){
 const [requestOpen,setRequestOpen]=useState(false);
 const [requestProjectId,setRequestProjectId]=useState(projectContext!=="all"?projectContext:workspaceProjects[0]?.id??"");
 const hasData=projectContext==="all"||projectContext==="proj_yunfu_prod_01"||projectContext==="proj_yunfu_eval_01";
 const projectLabel=projectName(projectContext,workspaceProjects);
 const requestProject=workspaceProjects.find(item=>item.id===(projectContext==="all"?requestProjectId:projectContext))??workspaceProjects[0];
 const canRequest=role==="Owner"||role==="Admin";
 const policyRows=projectContext==="all"?[
  ["客服播报","Project 策略","—","项目 RPM","318 / 500","返回 429","每分钟","订单权益",<Status key="s1">正常</Status>,<button key="a1" className="row-action" type="button" onClick={()=>notice("Project 是配额配置主体；当前为只读生效策略（Demo）")}>查看策略 →</button>],
  ["客服播报","客服生产服务","继承 Project","并发","37 / 80","排队 2 秒后拒绝","请求结束","订单权益",<Status key="s2">正常</Status>,<button key="a2" className="row-action" type="button" onClick={()=>notice("服务账号继承 Project 策略（Demo）")}>查看生效策略 →</button>],
  ["客服播报","播报调度服务","继承 Project","RPM","24 / 100","返回 429","每分钟","平台策略",<Status key="s3">正常</Status>,<button key="a3" className="row-action" type="button" onClick={()=>notice("服务账号继承 Project 策略（Demo）")}>查看生效策略 →</button>],
  ["内部评测","Project 策略","—","项目 RPM","42 / 100","返回 429","每分钟","订单权益",<Status key="s9">正常</Status>,<button key="a9" className="row-action" type="button" onClick={()=>notice("Project 是配额配置主体；当前为只读生效策略（Demo）")}>查看策略 →</button>],
  ["内部评测","评测流水线","继承 Project","RPM","42 / 100","返回 429","每分钟","平台策略",<Status key="s10">正常</Status>,<button key="a10" className="row-action" type="button" onClick={()=>notice("API Key 继承服务账号的有效策略（Demo）")}>查看生效策略 →</button>],
 ]:projectContext==="proj_yunfu_prod_01"?[
  [projectLabel,"Project 策略","—","项目 RPM","318 / 500","返回 429","每分钟","订单权益",<Status key="s4">正常</Status>,<button key="a4" className="row-action" type="button" onClick={()=>notice("当前 Project 策略由订单权益下发（Demo）")}>查看策略 →</button>],
  [projectLabel,"客服生产服务","继承 Project","并发","37 / 80","排队 2 秒后拒绝","请求结束","订单权益",<Status key="s5">正常</Status>,<button key="a5" className="row-action" type="button" onClick={()=>notice("服务账号没有独立配额表单，当前展示继承后的生效值（Demo）")}>查看生效策略 →</button>],
  [projectLabel,"播报调度服务","继承 Project","RPM","24 / 100","返回 429","每分钟","平台策略",<Status key="s6">正常</Status>,<button key="a6" className="row-action" type="button" onClick={()=>notice("服务账号没有独立配额表单，当前展示继承后的生效值（Demo）")}>查看生效策略 →</button>],
 ]:projectContext==="proj_yunfu_eval_01"?[
  [projectLabel,"Project 策略","—","项目 RPM","42 / 100","返回 429","每分钟","订单权益",<Status key="s7">正常</Status>,<button key="a7" className="row-action" type="button" onClick={()=>notice("当前 Project 策略由订单权益下发（Demo）")}>查看策略 →</button>],
  [projectLabel,"评测流水线","继承 Project","RPM","42 / 100","返回 429","每分钟","平台策略",<Status key="s8">正常</Status>,<button key="a8" className="row-action" type="button" onClick={()=>notice("API Key 继承服务账号的有效策略（Demo）")}>查看生效策略 →</button>],
 ]:[];
 const rpm=hasData?(projectContext==="all"?"360 / 600":projectContext==="proj_yunfu_eval_01"?"42 / 100":"318 / 500"):"0 / —";
 const concurrency=hasData?(projectContext==="all"?"37 / 100":projectContext==="proj_yunfu_eval_01"?"0 / 20":"37 / 80"):"0 / —";
 const chars=hasData?(projectContext==="all"?"155.08M":projectContext==="proj_yunfu_eval_01"?"26.44M":"128.64M"):"0";
 const throttled=hasData?(projectContext==="all"?"20":projectContext==="proj_yunfu_eval_01"?"2":"18"):"0";
 const openRequest=()=>{ if(!canRequest){notice("配额调整申请需要 Owner 或 Admin 发起（Demo）");return;} if(!requestProject){notice("请先创建或选择一个项目");return;} setRequestOpen(true); };
 return <><Tabs items={[{id:"projects" as View,label:"项目"},{id:"keys" as View,label:"API 凭证"},{id:"quota" as View,label:"配额与限流"},{id:"voices" as View,label:"音色授权"}]} active="quota" go={go}/><PageHeader title="配额与限流" description="Project 是配额配置主体；服务账号与 API Key 默认继承项目策略。此页查看生效水位，调整需提交申请。" action={<div className="page-actions">{projectContext==="all"?<select aria-label="申请项目" value={requestProjectId} onChange={event=>setRequestProjectId(event.target.value)}>{workspaceProjects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>:null}<button className="btn secondary" type="button" onClick={openRequest}>{canRequest?"申请调整策略":"联系 Owner / Admin"}</button></div>}/><section className="metric-grid"><Metric label="项目 RPM" value={rpm} meta={hasData?"分钟级重置":"尚未配置"} tone={hasData?"warn":undefined}/><Metric label="并发" value={concurrency} meta={hasData?"请求结束释放":"尚未配置"}/><Metric label="月度计量" value={chars} meta={hasData?"按量计费":"暂无计量事件"}/><Metric label="429 请求" value={throttled} meta={hasData?"近 24 小时":"当前项目"} tone={hasData?"warn":undefined}/></section>{hasData?<section className="panel table-panel"><DataTable caption="Project 有效限流策略" heads={["归属 Project","策略对象","继承关系","指标","当前 / 上限","耗尽策略","重置","规则来源","状态","操作"]} rows={policyRows}/></section>:<section className="panel empty-state compact"><Icon name="pulse" size={28}/><h3>当前项目暂无配额策略</h3><p>商务权益或平台策略尚未同步到该 Project，当前没有可展示的限流规则。</p></section>}{requestOpen&&requestProject?<QuotaRequestDialog projectName={requestProject.name} currentRpm={requestProject.id==="proj_yunfu_eval_01"?"42 / 100":"318 / 500"} currentConcurrency={requestProject.id==="proj_yunfu_eval_01"?"0 / 20":"37 / 80"} close={()=>setRequestOpen(false)} complete={summary=>{onQuotaRequest?.(requestProject.id,summary);notice("配额调整申请已提交，当前策略保持不变（Demo）");setRequestOpen(false)}}/>:null}</>;
}

function AccountCredentialsView({go,openKey,role,member,apiKeys,selectKey}:{go:(v:View)=>void;openKey:()=>void;role:Role;member:Member;apiKeys:ApiKeyRecord[];selectKey:(key:ApiKeyRecord)=>void}){
 const visible=apiKeys.filter(key=>role==="Owner"||role==="Admin"||key.createdBy===member.name||member.keyExposure?.includes(key.id));
 const canCreate=role==="Owner"||role==="Admin"||role==="Developer";
 return <><Tabs items={tabs} active="keys" go={go}/><PageHeader title="API 凭证" description="API Key 归属于 Member；同一账号下的多个 Key 共享 Voice、Token、RPM、TPM 与并发策略。" action={canCreate?<button className="btn primary" type="button" onClick={openKey}>创建 API Key</button>:<span className="period-chip">{role} · 只读</span>}/><section className="panel table-panel"><DataTable caption="API 凭证列表" heads={["名称 / Key","归属成员","Scope","有效期","最近调用","本月用量","状态","操作"]} rows={visible.map(key=>[<span className="cell-stack" key={key.id}><b>{key.name}</b><code>{key.masked}</code></span>,key.createdBy,<code key="scope">{key.scopes.join(", ")}</code>,key.expiresAt,key.lastUsedAt,key.usage,<Status key="state" tone={key.status==="已停用"?"bad":key.status==="轮换中"?"warn":"good"}>{key.status}</Status>,<button key="action" className="row-action" type="button" onClick={()=>{selectKey(key);go("keyDetail")}}>管理 →</button>])}/>{!visible.length?<div className="empty-state compact"><Icon name="key" size={28}/><h3>暂无可见 API Key</h3><p>创建或等待 Owner 为成员开通 API 凭证。</p></div>:null}</section></>;
}

export function AccountQuotaView({go,role,members,tabsItems}:{go:(v:View)=>void;role:Role;members:Member[];tabsItems?:{id:View;label:string}[]}){
 const activeMembers=members.filter(member=>member.status==="正常");
 const sum=(key:keyof ResourceAllocation)=>activeMembers.reduce((total,member)=>total+(member.allocation?.[key]??0),0);
 const remaining=(key:keyof ResourceAllocation)=>Math.max(0,(enterpriseEntitlements[key]??0)-sum(key));
 const rows=activeMembers.map(member=>{const a=member.allocation??{voice:0,token:0,rpm:0,tpm:0,concurrency:0};const u=member.usage??{voice:0,token:0,rpm:0,tpm:0,concurrency:0};return [<span className="cell-stack" key={member.email}><b>{member.name}</b><code>{member.email}</code></span>,member.role,`Voice ${u.voice} / ${a.voice}h`,`Token ${u.token} / ${a.token}M`,`${u.rpm} / ${a.rpm}`,`${u.tpm??0} / ${a.tpm??0}`,`${u.concurrency} / ${a.concurrency}`,<Status key="status" tone={a.rpm&&u.rpm/a.rpm>=.8?"warn":"good"}>{a.rpm&&u.rpm/a.rpm>=.8?"接近上限":"正常"}</Status>]});
 const resourceKeys:(keyof ResourceAllocation)[]=["voice","token","rpm","tpm","concurrency"];
 const pageTabs=tabsItems??tabs;
 return <><Tabs items={pageTabs} active="quota" go={go}/><PageHeader title="配额与限流" description="配额与限流以 Member 账号为执行主体；API Key 继承所属 Member 的资源策略。" action={<span className="period-chip">{role} · 企业资源池</span>}/><section className="metric-grid"><Metric label="Voice 资源池" value={`${sum("voice")} / ${enterpriseEntitlements.voice}h`} meta={`剩余 ${remaining("voice")}h`}/><Metric label="Token 资源池" value={`${sum("token")} / ${enterpriseEntitlements.token}M`} meta={`剩余 ${remaining("token")}M`}/><Metric label="RPM 资源池" value={`${sum("rpm")} / ${enterpriseEntitlements.rpm}`} meta={`剩余 ${remaining("rpm")} RPM`}/><Metric label="TPM 资源池" value={`${sum("tpm")} / ${(enterpriseEntitlements.tpm??0).toLocaleString()}`} meta={`剩余 ${remaining("tpm")} TPM`}/><Metric label="并发资源池" value={`${sum("concurrency")} / ${enterpriseEntitlements.concurrency}`} meta={`剩余 ${remaining("concurrency")} 路`}/></section><section className="panel allocation-ledger"><div className="panel-head"><div><span className="eyebrow">ENTERPRISE RESOURCE POOL</span><h2>企业权益池与分配状态</h2></div><span>Owner 在邀请或编辑成员时分配</span></div><div className="resource-ledger-grid">{resourceKeys.map(key=><div key={key}><span>{resourceLabels[key]}</span><b>{(enterpriseEntitlements[key]??0).toLocaleString()}</b><small>已分配 {sum(key).toLocaleString()} · 未分配 {remaining(key).toLocaleString()}</small><div className="meter"><i style={{width:`${Math.min(100,sum(key)/(enterpriseEntitlements[key]||1)*100)}%`}}/></div></div>)}</div></section><section className="panel table-panel"><div className="panel-head table-title"><div><h2>Member 生效配额</h2><span>当前账号水位 / 账号上限；429 与并发拒绝均按此策略判定</span></div></div><DataTable caption="Member 生效配额" heads={["成员账号","角色","Voice 用量 / 配额","Token 用量 / 配额","RPM 当前 / 上限","TPM 当前 / 上限","并发当前 / 上限","状态"]} rows={rows}/></section></>;
}

function ProjectDetail({go,project,apiKeys,setProjectContext}:{go:(v:View)=>void;project:WorkspaceProject;apiKeys:ApiKeyRecord[];setProjectContext:(project:ProjectContext)=>void}){
 const projectKeys=apiKeys.filter(key=>key.projectId===project.id);
 const rpmParts=project.rpm.split(" / ").map(Number),rpmPercent=rpmParts[1]?Math.round(rpmParts[0]/rpmParts[1]*100):0;
 const open=(target:View)=>{setProjectContext(project.id);go(target)};
 return <><button className="back" type="button" onClick={()=>go("projects")}>← 返回项目</button><PageHeader title={project.name} description="统一查看项目成员范围、API Key、配额与用量。" action={<button className="btn secondary" type="button" onClick={()=>notice("项目设置已打开（Demo）")}>项目设置</button>}/><section className="fact-grid panel"><div><span>Project ID</span><code>{project.id}</code></div><div><span>负责人</span><b>{project.owner}</b></div><div><span>成员范围</span><b>Owner / Admin / 已授权成员</b></div><div><span>状态</span><Status>{project.status}</Status></div></section><section className="metric-grid"><Metric label="API Keys" value={String(projectKeys.length)} meta={`${projectKeys.filter(key=>key.status==="有效").length} 个有效`}/><Metric label="本月用量" value={project.usage.replace(" 字符","")} meta="计费字符"/><Metric label="RPM 水位" value={`${rpmPercent}%`} meta={project.rpm} tone={rpmPercent>=60?"warn":undefined}/></section><section className="panel link-list"><button type="button" onClick={()=>open("keys")}><span><b>API Keys</b><small>{projectKeys.length?`${projectKeys.length} 个 Key · ${projectKeys.filter(key=>key.status==="有效").length} 个有效`:"创建第一个 API Key"}</small></span><Icon name="chevron"/></button><button type="button" onClick={()=>open("usage3")}><span><b>项目用量与费用</b><small>按项目、Key、模型下钻</small></span><Icon name="chevron"/></button></section></>
}
function KeyDetail({go,role,member,apiKey,updateKey}:{go:(v:View)=>void;role:Role;member:Member;apiKey:ApiKeyRecord;updateKey:(key:ApiKeyRecord,action:"rotate"|"disable")=>void}){
 const [lifecycle,setLifecycle]=useState<"rotate"|"disable"|null>(null);
 const disabled=apiKey.status==="已停用";
 const canManage=canManageCredentials(role,apiKey.projectId,member);
 const canRotate=canManage&&canAct(role,"key.rotate"),canDisable=canManage&&canAct(role,"key.disable");
 const action=canRotate||canDisable?<><button className="btn secondary" type="button" disabled={disabled||!canRotate} aria-disabled={disabled||!canRotate} onClick={()=>setLifecycle("rotate")}>轮换 Key</button><button className="btn danger" type="button" disabled={disabled||!canDisable} aria-disabled={disabled||!canDisable} onClick={()=>setLifecycle("disable")}>{disabled?"已停用":"停用 Key"}</button></>:<span className="period-chip">{role} · 只读</span>;
 return <><button className="back" type="button" onClick={()=>go("keys")}>← 返回 API Keys</button><PageHeader title={apiKey.name} description={`该 Key 直接归属项目“${apiKey.projectName}”，用于项目内服务调用。`} action={action}/><section className="fact-grid panel"><div><span>Key</span><code>{apiKey.masked}</code></div><div><span>Project</span><b>{apiKey.projectName}</b></div><div><span>状态</span><Status tone={disabled?"bad":apiKey.status==="轮换中"?"warn":"good"}>{apiKey.status}</Status></div></section><section className="two-col"><article className="panel detail-card"><span className="eyebrow">CREDENTIAL POLICY</span><h2>安全与调用 Scope</h2><dl><div><dt>Scope</dt><dd><code>{apiKey.scopes.join(", ")}</code></dd></div><div><dt>IP 白名单</dt><dd>{apiKey.ipAllowlist}</dd></div><div><dt>有效期</dt><dd>{apiKey.expiresAt}</dd></div><div><dt>密钥版本</dt><dd>v{apiKey.version}</dd></div></dl></article><article className="panel detail-card"><span className="eyebrow">LIFECYCLE & AUDIT</span><h2>生命周期与审计</h2><dl><div><dt>创建人 / 时间</dt><dd>{apiKey.createdBy} · {apiKey.createdAt}</dd></div><div><dt>最近轮换</dt><dd>{apiKey.lastRotatedAt}</dd></div><div><dt>最近调用</dt><dd>{apiKey.lastUsedAt}</dd></div><div><dt>本月用量</dt><dd>{apiKey.usage}</dd></div></dl></article></section><section className="panel table-panel key-exposure-panel"><div className="panel-head"><div><span className="eyebrow">EXPOSURE EVIDENCE</span><h2>完整值接触记录</h2></div><span>{apiKey.exposureEvents.length} 条 · 仅用于离职风险检查</span></div><DataTable caption="凭证暴露记录" heads={["成员账号","动作","Key 版本","时间"]} rows={apiKey.exposureEvents.map((event,index)=>[<span className="cell-stack" key={`${event.memberEmail}-${index}`}><b>{event.memberName}</b><code>{event.memberEmail}</code></span>,event.action,`v${event.version}`,event.at])}/></section>{lifecycle?<KeyLifecycleDialog mode={lifecycle} apiKey={apiKey} close={()=>setLifecycle(null)} complete={()=>{const mode=lifecycle;setLifecycle(null);const next=mode==="disable"?{...apiKey,status:"已停用" as const,lastUsedAt:"停用于刚刚"}:{...apiKey,status:"轮换中" as const,version:apiKey.version+1,lastRotatedAt:"刚刚",masked:"sk_live_••••YF26"};updateKey(next,mode);notice(mode==="disable"?`${apiKey.name} 已停用，后续调用将返回 401（Demo）`:`${apiKey.name} 已轮换，旧 Key 保留 24 小时迁移窗口（Demo）`)}}/>:null}</>
}
